#ifndef __JCC_H__
#define __JCC_H__

make_helper(ja_si_v);  
make_helper(jae_si_v);  
make_helper(jb_si_v);  
make_helper(jbe_si_v);  
make_helper(jc_si_v);  
make_helper(je_si_v);  
make_helper(jz_si_v);  
make_helper(jg_si_v);  
make_helper(jge_si_v);  
make_helper(jl_si_v);  
make_helper(jle_si_v);  
make_helper(jna_si_v);  
make_helper(jnae_si_v);  
make_helper(jnb_si_v);  
make_helper(jnbe_si_v);  
make_helper(jnc_si_v);  
make_helper(jne_si_v);  
make_helper(jng_si_v);  
make_helper(jnge_si_v);  
make_helper(jnl_si_v);  
make_helper(jnle_si_v);  
make_helper(jno_si_v);  
make_helper(jnp_si_v);  
make_helper(jns_si_v);  
make_helper(jnz_si_v);  
make_helper(jo_si_v);  
make_helper(jp_si_v);  
make_helper(jpe_si_v);  
make_helper(jpo_si_v); 
make_helper(js_si_v); 

make_helper(jcxz_si_b); 
make_helper(jecxz_si_b); 
make_helper(ja_si_b);  
make_helper(jae_si_b);  
make_helper(jb_si_b);  
make_helper(jbe_si_b);  
make_helper(jc_si_b);  
make_helper(je_si_b);  
make_helper(jz_si_b);  
make_helper(jg_si_b);  
make_helper(jge_si_b);  
make_helper(jl_si_b);  
make_helper(jle_si_b);  
make_helper(jna_si_b);  
make_helper(jnae_si_b);  
make_helper(jnb_si_b);  
make_helper(jnbe_si_b);  
make_helper(jnc_si_b);  
make_helper(jne_si_b);  
make_helper(jng_si_b);  
make_helper(jnge_si_b);  
make_helper(jnl_si_b);  
make_helper(jnle_si_b);  
make_helper(jno_si_b);  
make_helper(jnp_si_b);  
make_helper(jns_si_b);  
make_helper(jnz_si_b);  
make_helper(jo_si_b);  
make_helper(jp_si_b);  
make_helper(jpe_si_b);  
make_helper(jpo_si_b); 
make_helper(js_si_b); 

#endif
